agent: ragent

dataset:
  path: bdsaglam/musique-mini
  name: answerable
  split: validation

model:
  path: bdsaglam/Llama-3.1-8B-Instruct-ragent-grpo-musique-merged
  temperature: 0.5
  top_p: 0.95
  few_shot_prob: 0.0

retriever:
  name: hybrid-tei
  top_k: 1

repeat: 1

run: 1

devices: '1'