[project]
name = "vf-musique"
version = "0.0.2"
dependencies = [
    "verifiers>=0.1.2",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build]
include = ["vf_musique.py", "data_processing.py", "metrics.py", "rerank.py"]
