compute_environment: LOCAL_MACHINE
debug: false
distributed_type: MULTI_GPU
downcast_bf16: 'no'
machine_rank: 0
mixed_precision: bf16
num_machines: 1
num_processes: 3
rdzv_backend: static
same_network: true
use_cpu: false
