services:
  wiki-search:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8932:8000"
    environment:
      - HOST=0.0.0.0
      - PORT=8000
      - WEB_CONCURRENCY=1
    volumes:
      - ~/.cache/pyserini/indexes:/root/.cache/pyserini/indexes
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
  